const SUPABASE_URL = ""; // cole aqui sua URL do Supabase
const SUPABASE_ANON_KEY = ""; // cole aqui sua anon public key
const useSupabase = SUPABASE_URL && SUPABASE_ANON_KEY;
const supabaseClient = useSupabase ? supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const $=s=>document.querySelector(s); const app=$('#app');
let page='dashboard', q='', modal=null;
const labs=['Henrique','Optec','Magno','Casa','Outro'];
let db=JSON.parse(localStorage.getItem('otica_lumiere_db')||'{"clientes":[],"consertos":[]}');
function save(){localStorage.setItem('otica_lumiere_db',JSON.stringify(db))}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function today(){return new Date().toISOString().slice(0,10)}
function br(d){return d?d.split('-').reverse().join('/'):''}
function nextPedido(){return 'PED-'+String(db.clientes.length+1).padStart(6,'0')}
function nextOS(){return 'OS-'+String(db.consertos.length+1).padStart(5,'0')}
function statusBadge(s){let c=s==='Entregue'||s==='Pronto'?'b-ok':s==='Atrasado'?'b-bad':s==='Em laboratório'||s==='Em conserto'?'b-blue':'b-warn';return `<span class="badge ${c}">${s||'Pendente'}</span>`}
function filteredClientes(){return db.clientes.filter(c=>(c.nome+c.telefone+c.pedido).toLowerCase().includes(q.toLowerCase()))}
function stats(){let t=today();return{vendasDia:db.clientes.filter(c=>c.dataVenda===t).reduce((a,c)=>a+Number(c.valor||0),0),vendasMes:db.clientes.filter(c=>(c.dataVenda||'').slice(0,7)===t.slice(0,7)).reduce((a,c)=>a+Number(c.valor||0),0),lab:db.clientes.filter(c=>c.labStatus&&c.labStatus!=='Entregue').length,prontos:db.clientes.filter(c=>c.status==='Pronto para retirada').length,semArm:db.clientes.filter(c=>!c.armacaoRecebida).length,faltaExame:db.clientes.filter(c=>!c.exameRecebido).length,vencHoje:db.clientes.filter(c=>c.previsao===t&&c.status!=='Entregue').length,atrasados:db.clientes.filter(c=>c.previsao&&c.previsao<t&&c.status!=='Entregue').length,remarcados:db.clientes.filter(c=>c.remarcado).length,consertos:db.consertos.filter(c=>c.status!=='Entregue').length}}
function layout(content){app.innerHTML=`<div class="app"><aside class="side"><div class="brand">👓 Ótica Lumière</div><div class="menu">${[['dashboard','🏠 Dashboard'],['clientes','👥 Clientes'],['semarmacao','👓 Sem armação'],['faltaexame','📋 Falta exame'],['laboratorio','🧪 Laboratório'],['prazos','📅 Prazos'],['consertos','🔧 Consertos'],['financeiro','💰 Financeiro'],['relatorios','📊 Relatórios'],['config','⚙️ Configurações']].map(m=>`<button class="${page===m[0]?'active':''}" onclick="go('${m[0]}')">${m[1]}</button>`).join('')}</div></aside><main class="main">${content}</main></div>${modal||''}`}
window.go=p=>{page=p;modal=null;render()}
function render(){let s=stats();let head=`<div class="top"><div><h1>${title()}</h1><div class="muted">Sistema da Ótica Lumière</div></div><input class="search" placeholder="Buscar por nome, telefone ou pedido" value="${q}" oninput="q=this.value;render()"></div>`; if(page==='dashboard') return layout(head+dashboard(s)); if(page==='clientes')return layout(head+clientes()); if(page==='semarmacao')return layout(head+lista(c=>!c.armacaoRecebida,'armacao')); if(page==='faltaexame')return layout(head+lista(c=>!c.exameRecebido,'exame')); if(page==='laboratorio')return layout(head+lista(c=>c.laboratorio,'lab')); if(page==='prazos')return layout(head+prazos()); if(page==='consertos')return layout(head+consertos()); if(page==='financeiro')return layout(head+financeiro()); if(page==='relatorios')return layout(head+relatorios()); return layout(head+`<div class="card"><h3>Configurações</h3><p>Cole sua URL e chave do Supabase no arquivo <b>app.js</b>. O sistema também funciona offline com salvamento no navegador.</p></div>`)}
function title(){return {dashboard:'Dashboard',clientes:'Clientes',semarmacao:'Sem armação',faltaexame:'Falta exame',laboratorio:'Laboratório',prazos:'Controle de prazos',consertos:'Consertos',financeiro:'Financeiro',relatorios:'Relatórios',config:'Configurações'}[page]}
function dashboard(s){return `<div class="grid">${[['Vendas do dia',money(s.vendasDia)],['Vendas do mês',money(s.vendasMes)],['Em laboratório',s.lab],['Prontos',s.prontos],['Vencendo hoje',s.vencHoje],['Atrasados',s.atrasados],['Sem armação',s.semArm],['Falta exame',s.faltaExame],['Consertos',s.consertos],['Remarcados',s.remarcados]].map(x=>`<div class="card"><div class="num">${x[1]}</div><h3>${x[0]}</h3></div>`).join('')}</div><br><div class="card"><h3>Notificações</h3><p>🔴 ${s.atrasados} pedidos atrasados</p><p>🟡 ${s.vencHoje} vencendo hoje</p><p>👓 ${s.semArm} sem armação</p><p>📋 ${s.faltaExame} falta exame</p></div>`}
function clientes(){return `<button onclick="openCliente()">+ Novo cliente</button><br><br>${table(filteredClientes())}`}
function table(arr){return `<table class="table"><thead><tr><th>Pedido</th><th>Data</th><th>Cliente</th><th>Telefone</th><th>Laboratório</th><th>Status</th><th>Ações</th></tr></thead><tbody>${arr.map(c=>`<tr><td>${c.pedido}</td><td>${br(c.dataVenda)}</td><td>${c.nome}</td><td>${c.telefone||''}</td><td>${c.laboratorio||'-'}</td><td>${statusBadge(c.status)}</td><td class="actions"><button class="secondary" onclick="openCliente('${c.id}')">Editar</button><button class="secondary" onclick="whats('${c.telefone}')">Whats</button><button class="danger" onclick="delCliente('${c.id}')">Excluir</button></td></tr>`).join('')||'<tr><td colspan="7">Nenhum registro.</td></tr>'}</tbody></table>`}
function lista(fn,tipo){let arr=filteredClientes().filter(fn);return table(arr)+`<br><div class="muted">Use os botões de ação ao editar o cliente para atualizar armação, exame, laboratório e entrega.</div>`}
function prazos(){let t=today();let venc=filteredClientes().filter(c=>c.previsao===t&&c.status!=='Entregue'), atr=filteredClientes().filter(c=>c.previsao&&c.previsao<t&&c.status!=='Entregue'), rem=filteredClientes().filter(c=>c.remarcado);return `<h2>Vencendo hoje</h2>${table(venc)}<h2>Atrasados</h2>${table(atr)}<h2>Datas remarcadas</h2>${table(rem)}`}
function consertos(){return `<button onclick="openConserto()">+ Novo conserto</button><br><br><table class="table"><thead><tr><th>OS</th><th>Data</th><th>Cliente</th><th>Serviço</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>${db.consertos.map(c=>`<tr><td>${c.os}</td><td>${br(c.data)}</td><td>${c.nome}</td><td>${c.servico}</td><td>${money(c.valor)}</td><td>${statusBadge(c.status)}</td><td><button class="secondary" onclick="openConserto('${c.id}')">Editar</button></td></tr>`).join('')||'<tr><td colspan="7">Nenhum conserto.</td></tr>'}</tbody></table>`}
function financeiro(){let total=db.clientes.reduce((a,c)=>a+Number(c.valor||0),0), ent=db.clientes.reduce((a,c)=>a+Number(c.entrada||0),0);return `<div class="grid"><div class="card"><div class="num">${money(total)}</div><h3>Total vendido</h3></div><div class="card"><div class="num">${money(ent)}</div><h3>Entradas</h3></div><div class="card"><div class="num">${money(total-ent)}</div><h3>A receber</h3></div></div><br>${table(filteredClientes())}`}
function relatorios(){return `<div class="card"><h3>Relatórios</h3><p>Total de clientes: ${db.clientes.length}</p><p>Total de consertos: ${db.consertos.length}</p><p>Vendas do mês: ${money(stats().vendasMes)}</p><button onclick="window.print()">Imprimir relatório</button></div>`}
window.openCliente=(id)=>{let c=db.clientes.find(x=>x.id===id)||{id:crypto.randomUUID(),pedido:nextPedido(),dataVenda:today(),status:'Em laboratório',armacaoRecebida:false,exameRecebido:false,labStatus:'Aguardando envio'};modal=`<div class="modal"><div class="box"><h2>Cliente / Pedido</h2><div class="form">${field('pedido','Pedido',c.pedido,'readonly')} ${field('dataVenda','Data da venda',c.dataVenda,'date')} ${field('nome','Nome',c.nome||'')} ${field('telefone','Telefone/WhatsApp',c.telefone||'')} ${field('endereco','Endereço',c.endereco||'')} ${field('valor','Valor total',c.valor||0,'number')} ${field('entrada','Entrada',c.entrada||0,'number')}<div class="field"><label>Laboratório</label><select id="laboratorio">${labs.map(l=>`<option ${c.laboratorio===l?'selected':''}>${l}</option>`)}</select></div>${field('previsao','Previsão de entrega',c.previsao||'','date')}<div class="field"><label>Status</label><select id="status">${['Em laboratório','Pronto para retirada','Entregue','Atrasado'].map(x=>`<option ${c.status===x?'selected':''}>${x}</option>`)}</select></div>${field('remarcada','Nova data remarcada',c.remarcada||'','date')}<div class="field full"><label>Motivo/Observações</label><textarea id="obs">${c.obs||''}</textarea></div></div><br><div class="actions"><button onclick="saveCliente('${c.id}')">Salvar</button><button class="ok" onclick="mark('${c.id}','armacao')">Armação recebida</button><button class="ok" onclick="mark('${c.id}','exame')">Exame recebido</button><button class="secondary" onclick="modal=null;render()">Cancelar</button></div></div></div>`;render()}
function field(id,label,val,type='text'){let ro=type==='readonly'?'readonly':'';let tp=type==='readonly'?'text':type;return `<div class="field"><label>${label}</label><input id="${id}" type="${tp}" value="${val??''}" ${ro}></div>`}
window.saveCliente=(id)=>{let old=db.clientes.find(x=>x.id===id);let c={id,pedido:$('#pedido').value,dataVenda:$('#dataVenda').value,nome:$('#nome').value,telefone:$('#telefone').value,endereco:$('#endereco').value,valor:$('#valor').value,entrada:$('#entrada').value,laboratorio:$('#laboratorio').value,previsao:$('#previsao').value,status:$('#status').value,remarcada:$('#remarcada').value,remarcado:!!$('#remarcada').value,obs:$('#obs').value,armacaoRecebida:old?.armacaoRecebida||false,exameRecebido:old?.exameRecebido||false,labStatus:'Em produção'}; if(old) Object.assign(old,c); else db.clientes.push(c); save();modal=null;render()}
window.mark=(id,t)=>{let c=db.clientes.find(x=>x.id===id); if(!c){saveCliente(id); c=db.clientes.find(x=>x.id===id)} if(t==='armacao')c.armacaoRecebida=true; if(t==='exame')c.exameRecebido=true; save();modal=null;render()}
window.delCliente=id=>{if(confirm('Excluir cliente?')){db.clientes=db.clientes.filter(c=>c.id!==id);save();render()}}
window.whats=tel=>{let n=(tel||'').replace(/\D/g,''); if(n) location.href='https://wa.me/55'+n}
window.openConserto=(id)=>{let c=db.consertos.find(x=>x.id===id)||{id:crypto.randomUUID(),os:nextOS(),data:today(),status:'Recebido'};modal=`<div class="modal"><div class="box"><h2>Conserto</h2><div class="form">${field('os','OS',c.os,'readonly')}${field('data','Data',c.data,'date')}${field('nome','Cliente',c.nome||'')}${field('telefone','Telefone',c.telefone||'')}${field('servico','Serviço',c.servico||'')}${field('valor','Valor',c.valor||0,'number')}${field('entrada','Entrada',c.entrada||0,'number')}<div class="field"><label>Status</label><select id="status">${['Recebido','Em conserto','Aguardando peça','Pronto','Entregue'].map(x=>`<option ${c.status===x?'selected':''}>${x}</option>`)}</select></div><div class="field full"><label>Observações</label><textarea id="obs">${c.obs||''}</textarea></div></div><br><button onclick="saveConserto('${c.id}')">Salvar</button> <button class="secondary" onclick="modal=null;render()">Cancelar</button></div></div>`;render()}
window.saveConserto=(id)=>{let old=db.consertos.find(x=>x.id===id);let c={id,os:$('#os').value,data:$('#data').value,nome:$('#nome').value,telefone:$('#telefone').value,servico:$('#servico').value,valor:$('#valor').value,entrada:$('#entrada').value,status:$('#status').value,obs:$('#obs').value}; if(old)Object.assign(old,c); else db.consertos.push(c); save();modal=null;render()}
render();
